// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dal;

#nullable disable

namespace dal.Migrations
{
    [DbContext(typeof(PolitiekDbContext))]
    partial class PolitiekDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("models.Niveau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Niveaus");
                });

            modelBuilder.Entity("models.Politicus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("JarenDienst")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolitiekePartijNiveauID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolitiekePartijNiveauID");

                    b.ToTable("Politici");
                });

            modelBuilder.Entity("models.PolitiekePartij", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AantalLeden")
                        .HasColumnType("int");

                    b.Property<string>("PartijNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PolitiekePartijen");
                });

            modelBuilder.Entity("models.PolitiekePartijNiveau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NiveauID")
                        .HasColumnType("int");

                    b.Property<int>("PolitiekePartijID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NiveauID");

                    b.HasIndex("PolitiekePartijID");

                    b.ToTable("PolitiekePartijenNiveau");
                });

            modelBuilder.Entity("models.Politicus", b =>
                {
                    b.HasOne("models.PolitiekePartijNiveau", "PolitiekePartijNiveau")
                        .WithMany("Politici")
                        .HasForeignKey("PolitiekePartijNiveauID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolitiekePartijNiveau");
                });

            modelBuilder.Entity("models.PolitiekePartijNiveau", b =>
                {
                    b.HasOne("models.Niveau", "Niveau")
                        .WithMany("PolitiekePartijNiveaus")
                        .HasForeignKey("NiveauID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("models.PolitiekePartij", "PolitiekePartij")
                        .WithMany("PolitiekePartijNiveaus")
                        .HasForeignKey("PolitiekePartijID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Niveau");

                    b.Navigation("PolitiekePartij");
                });

            modelBuilder.Entity("models.Niveau", b =>
                {
                    b.Navigation("PolitiekePartijNiveaus");
                });

            modelBuilder.Entity("models.PolitiekePartij", b =>
                {
                    b.Navigation("PolitiekePartijNiveaus");
                });

            modelBuilder.Entity("models.PolitiekePartijNiveau", b =>
                {
                    b.Navigation("Politici");
                });
#pragma warning restore 612, 618
        }
    }
}
